<nav class="nav">
                <ul class="container nav_list">
                    <li><a href="#">Apple</a></li>
                    <li><a href="#">Samsung</a></li>
                    <li><a href="#">Philips</a></li>
                    <li><a href="#">Panasonic</a></li>
                    <li><a href="#">Honor</a></li>
                    <li><a href="#">Nokia</a></li>
                    <li><a href="#">LG</a></li>
                    <li><a href="#">Alcatel</a></li>
                    <li><a href="#">Lenovo</a></li>
                    <li><a href="#">Panasonic</a></li>
                    <li><a href="#">Honor</a></li>
                    <li><a href="#">Nokia</a></li>
                    <li><a href="#">LG</a></li>
                    <li><a href="#">Alcatel</a></li>
                    <li><a href="#">Lenovo</a></li>
                    <li><a href="#">Panasonic</a></li>
                    <li><a href="#">Honor</a></li>
                    <li><a href="#">Nokia</a></li>
                    <li><a href="#">LG</a></li>
                    <li><a href="#">Alcatel</a></li>
                    <li><a href="#">Lenovo</a></li>
                    <li><a href="#">Panasonic</a></li>
                    <li><a href="#">Honor</a></li>
                    <li><a href="#">Nokia</a></li>
                    <li><a href="#">LG</a></li>
                    <li><a href="#">Alcatel</a></li>
                    <li><a href="#">Lenovo</a></li>
                    <li><a href="#">Panasonic</a></li>
                    <li><a href="#">Honor</a></li>
                    <li><a href="#">Nokia</a></li>
                    <li><a href="#">LG</a></li>
                    <li><a href="#">Alcatel</a></li>
                    <li><a href="#">Lenovo</a></li>
                    <li><a href="#">Panasonic</a></li>
                </ul>
            </nav>